"""create ot_audit_records

Revision ID: 0cb7a7d5f517
Revises: 
Create Date: 2026-09-01 21:33:43.028369
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '0cb7a7d5f517'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_audit_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.Column('stage', sa.String(length=64), nullable=False),
    sa.Column('summary', sa.String(length=512), nullable=False),
    sa.Column('detail', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_audit_records_correlation_id'), 'ot_audit_records', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ot_audit_records_created_at'), 'ot_audit_records', ['created_at'], unique=False)
    op.create_index(op.f('ix_ot_audit_records_stage'), 'ot_audit_records', ['stage'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ot_audit_records_stage'), table_name='ot_audit_records')
    op.drop_index(op.f('ix_ot_audit_records_created_at'), table_name='ot_audit_records')
    op.drop_index(op.f('ix_ot_audit_records_correlation_id'), table_name='ot_audit_records')
    op.drop_table('ot_audit_records')
    # ### end Alembic commands ###
