"""create ot_screener_runs and ot_candidate_symbols

Revision ID: aa17079b801e
Revises: 0cb7a7d5f517
Create Date: 2026-09-03 21:42:46.515411
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'aa17079b801e'
down_revision: Union[str, None] = '0cb7a7d5f517'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_screener_runs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('universe_size', sa.Integer(), nullable=False),
    sa.Column('candidate_count', sa.Integer(), nullable=False),
    sa.Column('market_data_provider', sa.String(length=64), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_screener_runs_started_at'), 'ot_screener_runs', ['started_at'], unique=False)
    op.create_table('ot_candidate_symbols',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('run_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('reasons', sa.JSON(), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('source_freshness', sa.String(length=16), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['ot_screener_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_candidate_symbols_run_id'), 'ot_candidate_symbols', ['run_id'], unique=False)
    op.create_index(op.f('ix_ot_candidate_symbols_symbol'), 'ot_candidate_symbols', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ot_candidate_symbols_symbol'), table_name='ot_candidate_symbols')
    op.drop_index(op.f('ix_ot_candidate_symbols_run_id'), table_name='ot_candidate_symbols')
    op.drop_table('ot_candidate_symbols')
    op.drop_index(op.f('ix_ot_screener_runs_started_at'), table_name='ot_screener_runs')
    op.drop_table('ot_screener_runs')
    # ### end Alembic commands ###
