"""create ot_feature_snapshots

Revision ID: ca9cb5878a8a
Revises: aa17079b801e
Create Date: 2026-09-08 12:52:25.510715
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'ca9cb5878a8a'
down_revision: Union[str, None] = 'aa17079b801e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ot_feature_snapshots',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=16), nullable=False),
    sa.Column('as_of', sa.DateTime(timezone=True), nullable=False),
    sa.Column('feature_definition_version', sa.String(length=16), nullable=False),
    sa.Column('features', sa.JSON(), nullable=False),
    sa.Column('market_context', sa.JSON(), nullable=False),
    sa.Column('data_quality', sa.String(length=16), nullable=False),
    sa.Column('correlation_id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ot_feature_snapshots_as_of'), 'ot_feature_snapshots', ['as_of'], unique=False)
    op.create_index(op.f('ix_ot_feature_snapshots_correlation_id'), 'ot_feature_snapshots', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_ot_feature_snapshots_symbol'), 'ot_feature_snapshots', ['symbol'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ot_feature_snapshots_symbol'), table_name='ot_feature_snapshots')
    op.drop_index(op.f('ix_ot_feature_snapshots_correlation_id'), table_name='ot_feature_snapshots')
    op.drop_index(op.f('ix_ot_feature_snapshots_as_of'), table_name='ot_feature_snapshots')
    op.drop_table('ot_feature_snapshots')
    # ### end Alembic commands ###
